##
# The name of the package.
#
# It consists of vendor name and project name, separated by /.
#
name: empaphy/colorphul

##
# A short description of the package.
#
description: 'Color library for PHP'

##
# The license of the package.
#
license: MIT

##
# This defines the default behavior for filtering packages by stability.
#
# This defaults to stable, so if you rely on a dev package, you should specify
# it in your file to avoid surprises.
#
minimum-stability: stable

##
# Prefer more stable packages over unstable ones when finding compatible stable
# packages is possible.
#
# If you require a dev version or only alphas are available for a package, those
# will still be selected granted that the minimum-stability allows for it.
#
prefer-stable:     true

##
# Map of packages required by this package.
#
# The package will not be installed unless those requirements can be met.
#
require:
    php:                   ">=7.2"
    empaphy/composer-yaml: "^1.1"
    ext-bcmath:            "*"

require-dev:
    phpunit/phpunit: "^8.0"  # The PHP Unit Testing framework.

autoload:
    files:
        - "src/bcmath.php"

config:
    allow-plugins:
        empaphy/composer-yaml: true
